# -*- coding: utf-8 -*-
"""kaggle_ddos_ctgan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13G_uvHXzaU0g-GInOtEYjrVLJGhhA9f4
"""

# kaggle Ddos dataseti ile ctgan çalışması

# Colab: CTGAN ile hızlı prototip
!pip install -q ctgan pandas scikit-learn matplotlib seaborn umap-learn

import pandas as pd, numpy as np

pip install ctgan

# DATASET DOSYASINI GOOGLE DRİVE /tmp klasörüne unzip edilmesi
import shutil
from google.colab import drive

drive.mount("/content/gdrive")
# Change the code below if the path to the dataset is different for you.
shutil.unpack_archive("/content/gdrive/MyDrive/ddos_dataset.zip", "/tmp/")

# 1) CSV yükle (yolunu değiştir)
csv_path = r"/tmp/dataset_sdn.csv"   # kendi dosya yolunu yaz
df = pd.read_csv(csv_path, low_memory=False)
print(df.shape)
display(df.head())

# 2) Hedef ve ön-işlem (label tespiti, örnek)
target = None
for t in ['label','Label','class','Class','attack','Attack','target','Target','flow_label']:
    if t in df.columns:
        target = t
        break
if target is None:
    target = df.columns[-1]
print("target:", target)

# Basit: hedef numeric değilse encode et
y_raw = df[target]
if y_raw.dtype == object:
    df[target] = pd.factorize(y_raw)[0]

# 3) Kategorik değişkenleri tespit et (ctgan için kategori listesi oluştur)
cat_cols = df.select_dtypes(include=['object','category']).columns.tolist()
# Eğer label kategorikse cat_cols'a dahil etme (ctgan'da label'i conditional kullanacağız)
if target in cat_cols:
    cat_cols.remove(target)
print("categorical columns:", cat_cols)

# 4) Feature selection (opsiyonel) - örnek: RandomForest importance ile hızlı seçim
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
X = df.drop(columns=[target])
y = df[target]
# Basit numeric-only for RF feature importance (önce encoding)
X_enc = pd.get_dummies(X, drop_first=True)
X_train, X_val, y_train, y_val = train_test_split(X_enc, y, test_size=0.2, random_state=42, stratify=y)
rf = RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42, class_weight='balanced')
rf.fit(X_train, y_train)
imp = pd.Series(rf.feature_importances_, index=X_enc.columns).sort_values(ascending=False)
top_features = imp.head(10).index.tolist()   # örnek: top 10 seç
print("Top features seçildi:", len(top_features))

#Top features
print(top_features)

# 4) Sadece seçilen kolonlar + target'ı al
selected_features = [
    'dt','pktcount','bytecount','dur','tot_dur',
    'packetins','pktperflow','byteperflow','pktrate','tx_bytes'
]
use_cols = [c for c in selected_features if c in df.columns] + [target]
df_sel = df[use_cols].dropna()
print("Kullanılan kolonlar:", df_sel.columns.tolist())
print(df_sel.head())

# 5) Kategorik kolonları bul (ctgan için lazım)
cat_cols = df_sel.select_dtypes(include=['object','category']).columns.tolist()
if target in cat_cols:
    cat_cols.remove(target)   # label'i conditional yapacağız
print("Categorical columns:", cat_cols)

# 6) Eğer target kategorik ise factorize et (numeric label olsun)
if df_sel[target].dtype == object:
    df_sel[target] = pd.factorize(df_sel[target])[0]

# 7) CTGAN eğitimi
from ctgan import CTGAN

ctgan = CTGAN(epochs=5)  # 300 epoch örnek, hızlı denemelerde 50-100 yapabilirsin
ctgan.fit(df_sel, discrete_columns=cat_cols)

# 8) Sentetik veri üret
synthetic = ctgan.sample(len(df_sel))
print("Synthetic shape:", synthetic.shape)
print(synthetic.head())